# Generated by Django 6.1 on 2026-08-13 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('billing_address', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('stage', models.CharField(choices=[('INTAKE', 'Intake'), ('DESIGN', 'Design'), ('PERMITTING', 'Permitting'), ('INSTALLATION', 'Installation'), ('QA', 'QA'), ('COMPLETE', 'Complete')], db_index=True, default='INTAKE', max_length=20)),
                ('on_hold', models.BooleanField(db_index=True, default=False)),
                ('hold_reason', models.CharField(blank=True, max_length=255)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=10)),
                ('site_address', models.CharField(max_length=255)),
                ('site_city', models.CharField(max_length=80)),
                ('site_state', models.CharField(max_length=2)),
                ('site_postal_code', models.CharField(max_length=10)),
                ('system_size_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('panel_count', models.PositiveIntegerField(blank=True, null=True)),
                ('battery_count', models.PositiveIntegerField(default=0)),
                ('roof_type', models.CharField(blank=True, choices=[('COMP_SHINGLE', 'Composition shingle'), ('TILE', 'Tile'), ('METAL', 'Metal'), ('FLAT_TPO', 'Flat / TPO'), ('GROUND_MOUNT', 'Ground mount')], max_length=20)),
                ('utility_company', models.CharField(blank=True, max_length=120)),
                ('ahj', models.CharField(blank=True, help_text="The permitting body for the site's jurisdiction.", max_length=120, verbose_name='Authority having jurisdiction')),
                ('permit_number', models.CharField(blank=True, max_length=60)),
                ('target_completion_date', models.DateField(blank=True, db_index=True, null=True)),
                ('rework_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designer_jobs', to=settings.AUTH_USER_MODEL)),
                ('assigned_tech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_jobs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='jobs.customer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DESIGN_PACKAGE', 'Design package'), ('PERMIT', 'Permit'), ('SITE_PHOTO', 'Site photo'), ('INSPECTION', 'Inspection report'), ('OTHER', 'Other')], max_length=20)),
                ('stage', models.CharField(choices=[('INTAKE', 'Intake'), ('DESIGN', 'Design'), ('PERMITTING', 'Permitting'), ('INSTALLATION', 'Installation'), ('QA', 'QA'), ('COMPLETE', 'Complete')], help_text='The stage this document was produced for.', max_length=20)),
                ('file', models.FileField(blank=True, upload_to='job-documents/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='jobs.job')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('INTAKE', 'Intake'), ('DESIGN', 'Design'), ('PERMITTING', 'Permitting'), ('INSTALLATION', 'Installation'), ('QA', 'QA'), ('COMPLETE', 'Complete')], db_index=True, max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_done', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='jobs.job')),
            ],
            options={
                'ordering': ('stage', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='jobs.job')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StageTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(choices=[('INTAKE', 'Intake'), ('DESIGN', 'Design'), ('PERMITTING', 'Permitting'), ('INSTALLATION', 'Installation'), ('QA', 'QA'), ('COMPLETE', 'Complete')], max_length=20)),
                ('to_stage', models.CharField(choices=[('INTAKE', 'Intake'), ('DESIGN', 'Design'), ('PERMITTING', 'Permitting'), ('INSTALLATION', 'Installation'), ('QA', 'QA'), ('COMPLETE', 'Complete')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('was_forced', models.BooleanField(default=False, help_text='Admin overrode the stage-ownership rule.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='jobs.job')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['stage', 'target_completion_date'], name='job_stage_due_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['assigned_tech', 'stage'], name='job_tech_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['customer', 'stage'], name='job_customer_stage_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('rework_count__gte', 0)), name='job_rework_count_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='checklistitem',
            constraint=models.UniqueConstraint(fields=('job', 'stage', 'label'), name='checklist_item_unique_per_stage'),
        ),
        migrations.AddIndex(
            model_name='stagetransition',
            index=models.Index(fields=['job', 'created_at'], name='transition_job_time_idx'),
        ),
    ]
