# Generated by Django 6.1 on 2026-08-13 09:09

import apps.jobs.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, upload_to='job-documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp', 'heic', 'dwg']), apps.jobs.models.validate_document_size]),
        ),
    ]
